# Generated by Django 2.2.2 on 2019-06-24 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='work_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
