# Generated by Django 2.2.2 on 2019-06-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_app', '0002_services_work_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('category', models.ManyToManyField(to='companies_app.Services')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_app.Company')),
            ],
        ),
    ]
