# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
