# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_myuser_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_play',
            field=models.BooleanField(default=False),
        ),
    ]
